### ISSUE TITLE
Slack Environment

### ISSUE THREAD

**Issue by IMJONEZZ** [arnnis/Sup#1]
Wonderful app, thanks for open-sourcing!

What needs to go in the .env, so that a person can connect to their own Slack channel with the api, not just the supplayground?

Not asking you to give up any sensitive info, just wondering what the layout for it is.

**Comment by arnnis** [comment]
You can login to any slack worksapces from the login page. No need to edit the env.
Just fill the team field with your workspace domain.

**Comment by IMJONEZZ** [comment]
Thanks, I figured it out. It's because the password is passed in in all lowercase. If I take that out, it works fine.

2 more questions:
1. Scrolling is bugged on the web version on PC, since in the CSS it's set to "touch." Any ideas as to how to allow touch to work when accessed on mobile, but scroll to work when accessed otherwise?
2. Photo uploads aren't working locally, I haven't changed anything about it, the files just don't upload correctly for whatever reason, and they don't appear in the files tab. How can I fix that? The photos display correctly on the actual Slack channel.

**Comment by IMJONEZZ** [comment]
One other issue:
The emoji-market-native package causes a BABEL_ENV command issue. All of the other similar commands have cross-env in front of the BABEL_ENV except that one, any way you could change it in your private forked repository?

**Comment by arnnis** [comment]
Thanks I fixed the password lowercase issue, will release a new version today

There seems to be some ui bugs on windows only, it's fine on mac
I dont have access to a windows PC right now so feel free to send a pull request.

The emoji-mart issue occurs only on windows too, I came acrossed it when I was running the CI on Windows

I'm aware of images load problem, it was fine until last month but slack made a change to their API, now it gives CORS errors, Avatars are fine though! I'll try to find a workaround or ask Slack to fix it.

Please create seperate issues for each bug from now. Thanks.

**Comment by IMJONEZZ** [comment]
Sweet, thank you! I'll create a separate issue if I come across any others. Great work!
