### ISSUE TITLE
[Not an Issue] Contributing Question

### ISSUE THREAD

**Issue by itsammar-dev** [arnnis/Sup#5]
# Quick Question
So, I am interested in contributing to this project. Do I need to do anything specific when I send you a pull request. Like any specific commands? 

Thanks!

**Comment by arnnis** [comment]
Before sending pull requests, please test your code on at least one native platform (ios or android) and also web. if you have desktop specific code test that as well.

the commands to run the project for each platform is in Contributing section of readme.

that's all.

Thanks for your contribution :)
